class ConfigKeys:
    TLS_VERSIONS = "TLSVersionsConfig"
    URLS = "URLS"
    CRAWL_TIME = "CrawlTime"
    CHROME_PATH = "ChromePath"
    DRIVER_PATH = "DriverPath"
    SNIFF_FILTER = "SniffFilter"
    COOKIES = "Cookies"
    COOKIE_NAME = "Name"
    COOKIE_VALUE = "Value"
